services:
  results_view:
    build: LMS/Results_View_WebApp/
    ports:
      - "8080:80"
    environment:
      - HOSTNAME=results_view
    volumes:
      - ./LMS/Results_View_WebApp/frontend/.:/var/www/html/
    restart: always
  data_input:
    build: LMS/Data_Input_WebApp/
    ports:
      - "8081:80"
    environment:
      - HOSTNAME=data_input
    volumes:
      - ./LMS/Data_Input_WebApp/frontend:/var/www/html/
    restart: always
  # mysql:
  #   build: LMS/MySQL_DB/
  #   ports:
  #     - "1433:1433"
  # mongoDB:
  #   build: LMS/MongoDB/
  #   ports: 
  # authentication_service:
  #   build: LMS/Authentication_Service/
  #   ports: 
  # analytics_service:
  #   build: LMS/Analytics_Service/
  #   ports: 